function xe = ForwardKinematics(q1,q2,q3,q4,q5,q6)
%FORWARDKINEMATICS
%    XE = FORWARDKINEMATICS(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    23-Apr-2017 22:24:09

t2 = q1+q2;
t3 = cos(t2);
t4 = pi.*(1.1e1./7.2e1);
t5 = cos(t4);
t6 = 1.0./t5;
t7 = sin(t2);
t8 = pi.*(1.1e1./3.6e1);
t9 = q3+q4;
t10 = sin(t9);
t11 = sin(t8);
t12 = cos(q3);
t13 = t5.*4.146e3;
t14 = t13+7.43e2;
t15 = t5.*3.374e3;
t16 = t15+7.43e2;
t17 = cos(t8);
t18 = cos(q5);
t19 = cos(t9);
t20 = sin(q5);
t21 = cos(q6);
t22 = sin(q6);
t23 = t11.*t19;
t29 = t10.*t17.*t20;
t24 = t23-t29;
t26 = t17.*t19;
t27 = t10.*t11.*t20;
t28 = t26+t27;
t25 = t11.*t28+t17.*t21.*t24-t10.*t17.*t18.*t22;
t31 = t17.*t28;
t32 = t11.*t21.*t24;
t33 = t10.*t11.*t18.*t22;
t30 = t31-t32+t33;
xe = [t7.*(-9.8e-3)+t3.*t12.*(4.1e1./1.0e2)-t6.*t16.*(t3.*t10.*t17+t7.*t11.*t18-t3.*t11.*t19.*t20).*5.0e-5-t3.*t6.*t10.*7.43e-2-t6.*t7.*t14.*5.0e-5;t3.*9.8e-3+t7.*t12.*(4.1e1./1.0e2)+t6.*t16.*(t3.*t11.*t18-t7.*t10.*t17+t7.*t11.*t19.*t20).*5.0e-5+t3.*t6.*t14.*5.0e-5-t6.*t7.*t10.*7.43e-2;sin(q3).*(-4.1e1./1.0e2)-t6.*t19.*7.43e-2-t6.*t16.*(-t19+t5.^2.*t19.*2.0+t5.*t10.*t20.*sin(t4).*2.0).*5.0e-5+2.755e-1;angle(t3.*t20.*t21.*-1i+t7.*t20.*t21-t3.*t10.*t11.*t22-t7.*t10.*t11.*t22.*1i-t3.*t17.*t18.*t22.*1i+t3.*t18.*t19.*t21+t7.*t17.*t18.*t22+t7.*t18.*t19.*t21.*1i-t3.*t17.*t19.*t20.*t22-t7.*t17.*t19.*t20.*t22.*1i);angle(t22.*t24.*1i+sqrt(t25.^2+t30.^2)+t10.*t18.*t21.*1i);angle(-t31+t32-t33-t11.*t28.*1i-t17.*t21.*t24.*1i+t10.*t17.*t18.*t22.*1i)];
